<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>EcommercePlatform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EcommercePlatform.Domain\EcommercePlatform.Domain.csproj" />
    <ProjectReference Include="..\EcommercePlatform.TestBase\EcommercePlatform.TestBase.csproj" />
  </ItemGroup>

</Project>
