<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>EcommercePlatform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcommercePlatform.Domain\EcommercePlatform.Domain.csproj" />
    <ProjectReference Include="..\EcommercePlatform.Application.Contracts\EcommercePlatform.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Application" Version="8.0.4" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="8.0.4" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="8.0.4" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="8.0.4" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="8.0.4" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Products\Dtos\" />
  </ItemGroup>

</Project>
